### ISSUE TITLE
support for typeRGBColor

### ISSUE THREAD

**Issue by ronzo99** [hhas/SwiftAutomation#1]
I've implemented a local change and tested against my own app, which is a scriptable text editor. Here is my one added method to unpack RGB data and a change to unpackAsAny() that calls it, both in the file UnpackFuncs.swift.

	public func unpackAsRGBColor(_ descriptor: Descriptor) throws -> [Int] {
	
		guard descriptor.data.count == MemoryLayout<UInt16>.size * 3 
			else { throw AppleEventError.corruptData }

		let rgbColor:RGBColor = descriptor.data.withUnsafeBytes { buffer in
			buffer.bindMemory(to: RGBColor.self)[0]
		}
			
		let red   = Int(UInt16(bigEndian: rgbColor.red))
		let green = Int(UInt16(bigEndian: rgbColor.green))
		let blue  = Int(UInt16(bigEndian: rgbColor.blue))

		return [red, green, blue]
	}	

and in existing method UnpackAsAny

	public func unpackAsAny(_ descriptor: Descriptor) throws -> Any {
		...
		case typeRGBColor:
			result = try unpackAsRGBColor(descriptor)
		case typeQDPoint, typeQDRectangle:
			return try unpackAsArray(descriptor, using: unpackAsInt)
		...
	}

and in test project main.swift, add

	 print(try doc.text.color.set(to: [25186, 48058, 18246])) // 6-color Apple logo's green
	
	 print("TEST: get the color of text of doc")
	 print("// try doc.text.color.get()")
	 // print(try doc.text.color.get())  // WAS: Error -1700: Can't make some data into the expected type.: file
	 print(try doc.text.color.get())     // NOW: [25186, 48058, 18246]

**Comment by hhas** [comment]
Added in `AppleEvents` rev 6701830; please confirm this addresses the issue.

**Comment by ronzo99** [comment]
Yes, I pulled the new code and tested typeRGBColor using the set() and get() calls you added to the main.swift test scheme. 

I tested typeQDRectangle the same way, by adding this:
	print(try textedit.windows[0].bounds.get())

It was instructive to see the additional steps you took to integrate my suggestions into the framework. Figuring out the generic calling conventions was a bit beyond my skills, so thanks!

By the way, SwiftAutomation was mentioned by Mark Alldritt on the ScriptDebugger forum this week. https://forum.latenightsw.com/t/shortcuts-applescript/3162 <https://forum.latenightsw.com/t/shortcuts-applescript/3162>

-- Ron

***@***.***

On Jun 15, 2021, at 2:08 PM, hhas ***@***.***> wrote:


Added in AppleEvents rev 6701830; please confirm this addresses the issue.

**Comment by ronzo99** [comment]
Well, I couldn't have been wronger! :-)

unpackAsQDPoint crashes at buffer.bindMemory(to: Rect.self)[0]

The fix is to replace "Rect" with "Point" at two places in that line.

This can be tested by targeting Finder, which uses a point for its "desktop position" folder property:

let finder = Finder()
print("TEST: get desktop position of folder \"TEMP\"")
print(try finder.folders["TEMP"].desktopPosition.get()) // [2301, 554]

With this change, all three Carbon-related data types are unpacked correctly.

-- Ron

***@***.***



On Jun 15, 2021, at 4:02 PM, Ron Reuter ***@***.***> wrote:

Yes, I pulled the new code and tested typeRGBColor using the set() and get() calls you added to the main.swift test scheme. 

I also tested typeQDRectangle the same way, by adding this:
	print(try textedit.windows[0].bounds.get())

TextEdit doesn't seem to expose typeQDPoint anywhere, so I didn't test that. 
I did notice this odd code in unpackAsQDPoint:
	let point: Rect = ...

Since private struct Point was defined above, I wonder if you meant:
	let point: Point = ...

I imagine the code, as written, works fine, since the first two elements of a Rect are a Point (the origin), but I was not able to test it yet.

It was instructive to see the additional steps you took to integrate my suggestions into the framework. Figuring out the generic calling conventions was a bit beyond my skills, so thanks!

By the way, SwiftAutomation was mentioned by Mark Alldritt on the ScriptDebugger forum this week. https://forum.latenightsw.com/t/shortcuts-applescript/3162 <https://forum.latenightsw.com/t/shortcuts-applescript/3162>

-- Ron

***@***.*** ***@***.***>

On Jun 15, 2021, at 2:08 PM, hhas ***@***.*** ***@***.***>> wrote:


Added in AppleEvents rev 6701830; please confirm this addresses the issue.

**Comment by ronzo99** [comment]
> Added in `AppleEvents` rev 6701830; please confirm this addresses the issue.

unpackAsRGBColor now works as expected
