### ISSUE TITLE
unpackAsQDPoint crash

### ISSUE THREAD

**Issue by ronzo99** [hhas/SwiftAutomation#4]
unpackAsQDPoint crashes at:
    let point: Rect = descriptor.data.withUnsafeBytes { buffer in
        buffer.bindMemory(to: Rect.self)[0]

The fix is to replace "Rect" with "Point" at two places in that line.

This can be tested by targeting Finder, which uses a point for its "desktop position" folder property:

let finder = Finder()
print("TEST: get desktop position of folder \"TEMP\"")
print(try finder.folders["TEMP"].desktopPosition.get()) // [2301, 554]

**Comment by hhas** [comment]
Thanks for being thorough. Careless copy-paste error on my part. Fixed in `AppleEvents` rev e72f117.
